### ISSUE TITLE
Failed to parse group userif and firewall KAONMEDIA CG2200 CLARO

### ISSUE THREAD

**Issue by tolonuia** [jclehner/bcm2-utils#56]
I have a router provided by Claro, its a KAONMEDIA CG2200, this is a GatewaySettings.bin. bcm2cfg is having issues reading firewall and userif sections.
 
bcm2utils-v0.9.7-win32> ./bcm2cfg info GatewaySettings.bin
failed to parse group userif
failed to parse group firewall
GatewaySettings.bin
type    : gwsettings
profile : generic
checksum: 8c5b0bd2e0ef28a9e92706cdf9e632c3 (ok)
size    : 17909 (ok)

36535256  6SRV  0.1     grp_6srv       1354 b
52472e2e  RG..  0.32    rg             3328 b
4d4c6f67  MLog  0.9     userif         1563 b
4344502e  CDP.  1.7     dhcp           1811 b
46495245  FIRE  0.8     firewall         62 b
4353502e  CSP.  1.4     csp              53 b
66776672  fwfr  0.1     grp_fwfr          9 b
56504e47  VPNG  1.0     grp_vpng         15 b
38303231  8021  0.43    bcmwifi         789 b
38303232  8022  0.43    bcmwifi2        789 b
57694775  WiGu  0.15    guestwifi      4028 b
57694776  WiGv  0.15    guestwifi2     4028 b

**Comment by jclehner** [comment]
Your `userif` group uses a non-standard format. You can send me your `GatewaySettings.bin` file via email (joseph.c.lehner@gmail.com). Maybe I can work something out.

**Comment by jclehner** [comment]
The `userif` issue has been fixed. The `firewall` group still remains, but that is very low priority. Try this:

[bcm2-utils-v0.9.7-8-g7092373-win32.zip](https://github.com/jclehner/bcm2-utils/files/14185538/bcm2-utils-v0.9.7-8-g7092373-win32.zip)

**Comment by tolonuia** [comment]
Hello there, thank you for taking the time to help people in need like me. Im using the binary you shared but im still getting the same error.   

bcm2-utils-v0.9.7-8-g7092373-win32> ./bcm2cfg info GatewaySettings.bin
failed to parse group userif
failed to parse group firewall
GatewaySettings.bin
type    : gwsettings
profile : generic
checksum: 8c5b0bd2e0ef28a9e92706cdf9e632c3 (ok)
size    : 17909 (ok)

36535256  6SRV  0.1     grp_6srv       1354 b
52472e2e  RG..  0.32    rg             3328 b
4d4c6f67  MLog  0.9     userif         1563 b
4344502e  CDP.  1.7     dhcp           1811 b
46495245  FIRE  0.8     firewall         62 b
4353502e  CSP.  1.4     csp              53 b
66776672  fwfr  0.1     grp_fwfr          9 b
56504e47  VPNG  1.0     grp_vpng         15 b
38303231  8021  0.43    bcmwifi         789 b
38303232  8022  0.43    bcmwifi2        789 b
57694775  WiGu  0.15    guestwifi      4028 b
57694776  WiGv  0.15    guestwifi2     4028 b

and when I try to retrieve userif info I get this:

bcm2-utils-v0.9.7-8-g7092373-win32> ./bcm2cfg type GatewaySettings.bin userif
failed to parse group userif
failed to parse group firewall
group[4d4c6f67]

also trying to list:

bcm2-utils-v0.9.7-8-g7092373-win32> ./bcm2cfg list GatewaySettings.bin userif
failed to parse group userif
failed to parse group firewall
userif._data

when i try to read userif._data i get this:

bcm2-utils-v0.9.7-8-g7092373-win32> ./bcm2cfg get GatewaySettings.bin userif._data
failed to parse group userif
failed to parse group firewall
userif._data = {
  0x000 = 00:05:61:64:6D:69:6E:00:05:61:64:6D:69:6E:00:05:61:64:6D:69:6E:00:05:43
  0x018 = 6C:40:72:30:00:04:75:73:65:72:00:04:75:73:65:72:00:05:61:64:6D:69:6E:00
  0x030 = 05:43:6C:40:72:30:02:61:64:6D:69:6E:00:00:00:00:00:00:00:00:00:00:00:61
  0x048 = 64:6D:69:6E:00:00:00:00:00:00:00:00:00:00:00:31:32:33:34:35:36:37:38:39
  0x060 = 30:41:42:43:44:45:46:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:43
  0x078 = 6C:40:72:30:00:00:00:00:00:00:00:00:00:00:00:43:6C:40:72:30:00:00:00:00
  0x090 = 00:00:00:00:00:00:00:43:6C:40:72:30:00:00:00:00:00:00:00:00:00:00:00:13
  0x0a8 = 13:00:00:02:58:12:14:00:00:00:38:0A:91:00:01:0A:91:FF:FE:D8:E6:96:69:D8
  0x0c0 = E6:96:6E:C8:06:C0:09:C8:06:C0:0E:BE:94:0F:DC:BE:94:0F:DC:0A:DA:CB:71:0A
  0x0d8 = DA:CB:76:0A:1F:D2:11:0A:1F:D2:16:0A:1F:DD:E9:0A:1F:DD:EE:00:00:02:58:01
  0x0f0 = 00:03:73:70:61:53:54:42:2D:49:50:54:56:00:00:00:00:00:00:00:00:00:00:00
  0x108 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x120 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x138 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x150 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x168 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x180 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x198 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x1b0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x1c8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x1e0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x1f8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x210 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x228 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x240 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x258 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x270 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x288 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x2a0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x2b8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x2d0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x2e8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x300 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x318 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x330 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x348 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x360 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x378 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x390 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x3a8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x3c0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x3d8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x3f0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x408 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x420 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x438 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x450 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x468 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x480 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x498 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x4b0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x4c8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x4e0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x4f8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x510 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x528 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x540 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x558 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x570 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x588 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x5a0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x5b8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x5d0 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x5e8 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
  0x600 = 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00

based on online hexe readers it is roughly translated to: 

admin. admin. admin.. CL@ro .us er.. user.. admin.. CL@ro.admin... admin.. 123456789 ABCDEF.... CL@ro..... CL@ro........ X... 8....... n........ q.v......... X... spaSTB-IPTV...


any help again will be greatly appreciated, still cant open telnet port 🙏

**Comment by jclehner** [comment]
Forgot to mention: for this to work, you'll have to manually specify the profile (using `-P cg2200`):
```
$ bcm2cfg -P cg2200 get GatewaySettings.bin userif
failed to parse group firewall
userif = {
  http_user = "admin"
  http_pass = "admin"
  http_admin_user = "admin"
  http_admin_pass = "Cl@r0"
  http_local_user = "user"
  http_local_pass = "user"
  http_default_user = "admin"
  http_default_pass = "Cl@r0"
  remote_acc_methods = http
  remote_acc_user = "admin"
  remote_acc_pass = "admin"
  telnet_ipstacks = IP1 | IP2 | IP5
  ssh_ipstacks = IP1 | IP2 | IP5
  remote_acc_timeout = 600
  http_ipstacks = IP2 | IP5
  http_adv_ipstacks = IP3 | IP5
  http_seed = ""
  http_acl_hosts = {
    0x000 = 0A:E9:00:01:0A:E9:FF:FE:D8:E6:96:69:D8:E6:96:6E:C8:06:C0:09:C8:06:C0:0E
    0x018 = BE:94:0F:DC:BE:94:0F:DC:0A:DA:CB:71:0A:DA:CB:76:0A:1F:D2:11:0A:1F:D2:16
    0x030 = 0A:1F:DD:E9:0A:1F:DD:EE
  }
  http_idle_timeout = 600
  log_exceptions = yes
}
```

**Comment by tolonuia** [comment]
Thank you so much for this amazing job you do. And Im sorry to bother you again, but when I try to set any of the other two remote access types I get error.

- OPTIONS -

bcm2-utils-v0.9.7-8-g7092373-win32> ./bcm2cfg -P cg2200 type GatewaySettings.bin userif.remote_acc_methods
failed to parse group firewall
remote_acc_methods {
  0x00000001 = telnet
  0x00000002 = http
  0x00000004 = ssh

- WHAT IT IS RIGHT NOW -

bcm2-utils-v0.9.7-8-g7092373-win32> ./bcm2cfg -P cg2200 get GatewaySettings.bin userif.remote_acc_methods
failed to parse group firewall
userif.remote_acc_methods = http

- WHAT I TRY TO SET IT TO -

bcm2-utils-v0.9.7-8-g7092373-win32> ./bcm2cfg -P cg2200 set GatewaySettings.bin userif.remote_acc_methods telnet
failed to parse group firewall
userif.remote_acc_methods = telnet
error: value exceeds maximum of target type

I cant seem to be able to modify the telnet port nor ssh (i tried too). Any advise? Or maybe I am doing something wrong?

Thank you for helping me.

PD: Before bothering you with my questions I tried googling answer but I couldn't find anything related to the topic.

**Comment by jclehner** [comment]
> Note that a bug in the previous version prevents you from modifying the file. I've attached an update below:
> [bcm2-utils-v0.9.7-15-g5188041-win32.zip](https://github.com/jclehner/bcm2-utils/files/14241237/bcm2-utils-v0.9.7-15-g5188041-win32.zip)
